### ISSUE TITLE
La seccion "mi perfil" no es responsive 

### ISSUE THREAD

**Issue by DRVR1** [DRVR1/SistemaDeTurnosBackend#2]
![image](https://github.com/user-attachments/assets/2796cf73-8e18-463f-b84c-6b3ed9360dc9)

**Comment by IGVR1** [comment]
![image](https://github.com/user-attachments/assets/f7bf3b6f-37ea-45c1-89c1-5fdba4693137)
![image](https://github.com/user-attachments/assets/4a7ea348-7761-42cd-9643-3239a3216681)

Se pierde info al cambiar el tamaño asi q por ahora lo dejo en flex column
